import React from 'react'
import Enzyme, { mount } from 'enzyme'
import Adapter from '@wojtekmaj/enzyme-adapter-react-17'
import { ErrorBoundary } from './ErrorBoundary'

Enzyme.configure({ adapter: new Adapter() })

const ComponentWithError = (): JSX.Element => {
    return  <div>
                <script>throw new Error('Test error!')</script> 
            </div>
}

describe('ErrorBoundary: wrapper',()=> {
  
    test('displays error message on error generated by child', () => {
        const wrapper = mount(
            <ErrorBoundary > 
                <ComponentWithError />
            </ErrorBoundary> 
      )
      expect(wrapper.find(ComponentWithError)).toHaveLength(1)
  })

})