export enum Actions {
    APPLOAD = 'APPLOAD',
    SIGNUP = 'SIGNUP',
    LOGOUT = 'LOGOUT',
    SIGNIN = 'SIGNIN',
    SAND_THEME = 'SAND_THEME',
    STONE_THEME = 'STONE_THEME',
    BASIC_THEME = 'BASIC_THEME',
    APP_THEME_DARK = 'APP_THEME_DARK',
    APP_THEME_LIGHT = 'APP_THEME_LIGHT'
}
